"""
静态合约列表 - 当API无法获取时使用
包含欧易和币安全部USDT永续合约，不定期更新
"""
# 统计信息
# 欧易币安共有合约：247个。
# 更新时间：2026-06-17 13:06:35

OKX_USDT_SWAPS = [
    "0G-USDT-SWAP", "1INCH-USDT-SWAP", "2Z-USDT-SWAP", "A-USDT-SWAP", "AAVE-USDT-SWAP", "ACH-USDT-SWAP", "ACT-USDT-SWAP", "ACU-USDT-SWAP", "ADA-USDT-SWAP", "AERO-USDT-SWAP",
    "AEVO-USDT-SWAP", "AGLD-USDT-SWAP", "AIXBT-USDT-SWAP", "ALGO-USDT-SWAP", "ALLO-USDT-SWAP", "ANIME-USDT-SWAP", "APE-USDT-SWAP", "API3-USDT-SWAP", "APR-USDT-SWAP", "APT-USDT-SWAP",
    "AR-USDT-SWAP", "ARB-USDT-SWAP", "ARKM-USDT-SWAP", "ASTER-USDT-SWAP", "AT-USDT-SWAP", "ATH-USDT-SWAP", "ATOM-USDT-SWAP", "AUCTION-USDT-SWAP", "AVAX-USDT-SWAP", "AVNT-USDT-SWAP",
    "AXS-USDT-SWAP", "AZTEC-USDT-SWAP", "BABY-USDT-SWAP", "BAND-USDT-SWAP", "BARD-USDT-SWAP", "BASED-USDT-SWAP", "BAT-USDT-SWAP", "BCH-USDT-SWAP", "BEAT-USDT-SWAP",
    "BERA-USDT-SWAP", "BICO-USDT-SWAP", "BIGTIME-USDT-SWAP", "BILL-USDT-SWAP", "BIO-USDT-SWAP", "BLUR-USDT-SWAP", "BNB-USDT-SWAP", "BOME-USDT-SWAP", "BRETT-USDT-SWAP", "BREV-USDT-SWAP",
    "BSB-USDT-SWAP", "BTC-USDT-SWAP", "CC-USDT-SWAP", "CELO-USDT-SWAP", "CFX-USDT-SWAP", "CHIP-USDT-SWAP", "CHZ-USDT-SWAP", "COAI-USDT-SWAP", "COMP-USDT-SWAP", "CRV-USDT-SWAP",
    "CVX-USDT-SWAP", "DASH-USDT-SWAP", "DOGE-USDT-SWAP", "DOOD-USDT-SWAP", "DOT-USDT-SWAP", "DYDX-USDT-SWAP", "EDEN-USDT-SWAP", "EDGE-USDT-SWAP", "EGLD-USDT-SWAP", "EIGEN-USDT-SWAP",
    "ENA-USDT-SWAP", "ENJ-USDT-SWAP", "ENS-USDT-SWAP", "ENSO-USDT-SWAP", "ESP-USDT-SWAP", "ETC-USDT-SWAP", "ETH-USDT-SWAP", "ETHFI-USDT-SWAP", "ETHW-USDT-SWAP", "F-USDT-SWAP",
    "FARTCOIN-USDT-SWAP", "FIL-USDT-SWAP", "FLOW-USDT-SWAP", "FOGO-USDT-SWAP", "GALA-USDT-SWAP", "GAS-USDT-SWAP", "GIGGLE-USDT-SWAP", "GLM-USDT-SWAP", "GMT-USDT-SWAP", "GMX-USDT-SWAP",
    "GPS-USDT-SWAP", "GRASS-USDT-SWAP", "GRT-USDT-SWAP", "H-USDT-SWAP", "HBAR-USDT-SWAP", "HMSTR-USDT-SWAP", "HOME-USDT-SWAP", "HUMA-USDT-SWAP", "HYPE-USDT-SWAP", "ICP-USDT-SWAP",
    "ICX-USDT-SWAP", "IMX-USDT-SWAP", "INIT-USDT-SWAP", "INJ-USDT-SWAP", "IOST-USDT-SWAP", "IOTA-USDT-SWAP", "IP-USDT-SWAP", "IRYS-USDT-SWAP", "JELLYJELLY-USDT-SWAP", "JTO-USDT-SWAP",
    "JUP-USDT-SWAP", "KAITO-USDT-SWAP", "KAT-USDT-SWAP", "KGEN-USDT-SWAP", "KITE-USDT-SWAP", "KMNO-USDT-SWAP", "KSM-USDT-SWAP", "LA-USDT-SWAP", "LAB-USDT-SWAP", "LAYER-USDT-SWAP",
    "LDO-USDT-SWAP", "LIGHT-USDT-SWAP", "LINEA-USDT-SWAP", "LINK-USDT-SWAP", "LIT-USDT-SWAP", "LPT-USDT-SWAP", "LQTY-USDT-SWAP", "LTC-USDT-SWAP", "MAGIC-USDT-SWAP", "MANA-USDT-SWAP",
    "MASK-USDT-SWAP", "ME-USDT-SWAP", "MEGA-USDT-SWAP", "MEME-USDT-SWAP", "MERL-USDT-SWAP", "MET-USDT-SWAP", "METIS-USDT-SWAP", "MEW-USDT-SWAP", "MINA-USDT-SWAP", "MMT-USDT-SWAP",
    "MON-USDT-SWAP", "MOODENG-USDT-SWAP", "MORPHO-USDT-SWAP", "MOVE-USDT-SWAP", "MUBARAK-USDT-SWAP", "NEAR-USDT-SWAP", "NEIRO-USDT-SWAP", "NEO-USDT-SWAP", "NIGHT-USDT-SWAP", "NMR-USDT-SWAP",
    "NOT-USDT-SWAP", "ONDO-USDT-SWAP", "ONE-USDT-SWAP", "ONT-USDT-SWAP", "OP-USDT-SWAP", "OPG-USDT-SWAP", "OPN-USDT-SWAP", "ORDER-USDT-SWAP", "ORDI-USDT-SWAP", "PARTI-USDT-SWAP",
    "PENDLE-USDT-SWAP", "PENGU-USDT-SWAP", "PEOPLE-USDT-SWAP", "PIEVERSE-USDT-SWAP", "PIPPIN-USDT-SWAP", "PLUME-USDT-SWAP", "PNUT-USDT-SWAP", "POL-USDT-SWAP", "POPCAT-USDT-SWAP", "PROVE-USDT-SWAP",
    "PUMP-USDT-SWAP", "PYTH-USDT-SWAP", "QTUM-USDT-SWAP", "RAVE-USDT-SWAP", "RECALL-USDT-SWAP", "RENDER-USDT-SWAP", "RESOLV-USDT-SWAP", "RIVER-USDT-SWAP", "ROBO-USDT-SWAP",
    "RSR-USDT-SWAP", "RVN-USDT-SWAP", "S-USDT-SWAP", "SAHARA-USDT-SWAP", "SAND-USDT-SWAP", "SAPIEN-USDT-SWAP", "SEI-USDT-SWAP", "SENT-USDT-SWAP", "SHELL-USDT-SWAP", "SIGN-USDT-SWAP",
    "SKY-USDT-SWAP", "SLX-USDT-SWAP", "SNX-USDT-SWAP", "SOL-USDT-SWAP", "SOON-USDT-SWAP", "SOPH-USDT-SWAP", "SPACE-USDT-SWAP", "SPK-USDT-SWAP", "SPX-USDT-SWAP", "SSV-USDT-SWAP",
    "STABLE-USDT-SWAP", "STRK-USDT-SWAP", "STX-USDT-SWAP", "SUI-USDT-SWAP", "SUSHI-USDT-SWAP", "SYRUP-USDT-SWAP", "TAO-USDT-SWAP", "THETA-USDT-SWAP", "TIA-USDT-SWAP", "TRB-USDT-SWAP",
    "TRIA-USDT-SWAP", "TRUMP-USDT-SWAP", "TRUST-USDT-SWAP", "TRUTH-USDT-SWAP", "TRX-USDT-SWAP", "TURBO-USDT-SWAP", "UB-USDT-SWAP", "UMA-USDT-SWAP", "UNI-USDT-SWAP", "USDC-USDT-SWAP",
    "USELESS-USDT-SWAP", "VANA-USDT-SWAP", "VIRTUAL-USDT-SWAP", "W-USDT-SWAP", "WAL-USDT-SWAP", "WCT-USDT-SWAP", "WET-USDT-SWAP", "WIF-USDT-SWAP", "WLD-USDT-SWAP", "WLFI-USDT-SWAP",
    "WOO-USDT-SWAP", "XLM-USDT-SWAP", "XPL-USDT-SWAP", "XRP-USDT-SWAP", "XTZ-USDT-SWAP", "YB-USDT-SWAP", "YFI-USDT-SWAP", "YGG-USDT-SWAP", "ZAMA-USDT-SWAP", "ZBT-USDT-SWAP",
    "ZEC-USDT-SWAP", "ZEN-USDT-SWAP", "ZETA-USDT-SWAP", "ZIL-USDT-SWAP", "ZK-USDT-SWAP", "ZKP-USDT-SWAP", "ZORA-USDT-SWAP", "ZRO-USDT-SWAP", "ZRX-USDT-SWAP"
]    

BINANCE_USDT_PERPETUALS = [
    "0GUSDT", "1INCHUSDT", "2ZUSDT", "AUSDT", "AAVEUSDT", "ACHUSDT", "ACTUSDT", "ACUUSDT", "ADAUSDT", "AEROUSDT",
    "AEVOUSDT", "AGLDUSDT", "AIXBTUSDT", "ALGOUSDT", "ALLOUSDT", "ANIMEUSDT", "APEUSDT", "API3USDT", "APRUSDT", "APTUSDT",
    "ARUSDT", "ARBUSDT", "ARKMUSDT", "ASTERUSDT", "ATUSDT", "ATHUSDT", "ATOMUSDT", "AUCTIONUSDT", "AVAXUSDT", "AVNTUSDT",
    "AXSUSDT", "AZTECUSDT", "BABYUSDT", "BANDUSDT", "BARDUSDT", "BASEDUSDT", "BATUSDT", "BCHUSDT", "BEATUSDT",
    "BERAUSDT", "BICOUSDT", "BIGTIMEUSDT", "BILLUSDT", "BIOUSDT", "BLURUSDT", "BNBUSDT", "BOMEUSDT", "BRETTUSDT", "BREVUSDT",
    "BSBUSDT", "BTCUSDT", "CCUSDT", "CELOUSDT", "CFXUSDT", "CHIPUSDT", "CHZUSDT", "COAIUSDT", "COMPUSDT", "CRVUSDT",
    "CVXUSDT", "DASHUSDT", "DOGEUSDT", "DOODUSDT", "DOTUSDT", "DYDXUSDT", "EDENUSDT", "EDGEUSDT", "EGLDUSDT", "EIGENUSDT",
    "ENAUSDT", "ENJUSDT", "ENSUSDT", "ENSOUSDT", "ESPUSDT", "ETCUSDT", "ETHUSDT", "ETHFIUSDT", "ETHWUSDT", "FUSDT",
    "FARTCOINUSDT", "FILUSDT", "FLOWUSDT", "FOGOUSDT", "GALAUSDT", "GASUSDT", "GIGGLEUSDT", "GLMUSDT", "GMTUSDT", "GMXUSDT",
    "GPSUSDT", "GRASSUSDT", "GRTUSDT", "HUSDT", "HBARUSDT", "HMSTRUSDT", "HOMEUSDT", "HUMAUSDT", "HYPEUSDT", "ICPUSDT",
    "ICXUSDT", "IMXUSDT", "INITUSDT", "INJUSDT", "IOSTUSDT", "IOTAUSDT", "IPUSDT", "IRYSUSDT", "JELLYJELLYUSDT", "JTOUSDT",
    "JUPUSDT", "KAITOUSDT", "KATUSDT", "KGENUSDT", "KITEUSDT", "KMNOUSDT", "KSMUSDT", "LAUSDT", "LABUSDT", "LAYERUSDT",
    "LDOUSDT", "LIGHTUSDT", "LINEAUSDT", "LINKUSDT", "LITUSDT", "LPTUSDT", "LQTYUSDT", "LTCUSDT", "MAGICUSDT", "MANAUSDT",
    "MASKUSDT", "MEUSDT", "MEGAUSDT", "MEMEUSDT", "MERLUSDT", "METUSDT", "METISUSDT", "MEWUSDT", "MINAUSDT", "MMTUSDT",
    "MONUSDT", "MOODENGUSDT", "MORPHOUSDT", "MOVEUSDT", "MUBARAKUSDT", "NEARUSDT", "NEIROUSDT", "NEOUSDT", "NIGHTUSDT", "NMRUSDT",
    "NOTUSDT", "ONDOUSDT", "ONEUSDT", "ONTUSDT", "OPUSDT", "OPGUSDT", "OPNUSDT", "ORDERUSDT", "ORDIUSDT", "PARTIUSDT",
    "PENDLEUSDT", "PENGUUSDT", "PEOPLEUSDT", "PIEVERSEUSDT", "PIPPINUSDT", "PLUMEUSDT", "PNUTUSDT", "POLUSDT", "POPCATUSDT", "PROVEUSDT",
    "PUMPUSDT", "PYTHUSDT", "QTUMUSDT", "RAVEUSDT", "RECALLUSDT", "RENDERUSDT", "RESOLVUSDT", "RIVERUSDT", "ROBOUSDT",
    "RSRUSDT", "RVNUSDT", "SUSDT", "SAHARAUSDT", "SANDUSDT", "SAPIENUSDT", "SEIUSDT", "SENTUSDT", "SHELLUSDT", "SIGNUSDT",
    "SKYUSDT", "SLXUSDT", "SNXUSDT", "SOLUSDT", "SOONUSDT", "SOPHUSDT", "SPACEUSDT", "SPKUSDT", "SPXUSDT", "SSVUSDT",
    "STABLEUSDT", "STRKUSDT", "STXUSDT", "SUIUSDT", "SUSHIUSDT", "SYRUPUSDT", "TAOUSDT", "THETAUSDT", "TIAUSDT", "TRBUSDT",
    "TRIAUSDT", "TRUMPUSDT", "TRUSTUSDT", "TRUTHUSDT", "TRXUSDT", "TURBOUSDT", "UBUSDT", "UMAUSDT", "UNIUSDT", "USDCUSDT",
    "USELESSUSDT", "VANAUSDT", "VIRTUALUSDT", "WUSDT", "WALUSDT", "WCTUSDT", "WETUSDT", "WIFUSDT", "WLDUSDT", "WLFIUSDT",
    "WOOUSDT", "XLMUSDT", "XPLUSDT", "XRPUSDT", "XTZUSDT", "YBUSDT", "YFIUSDT", "YGGUSDT", "ZAMAUSDT", "ZBTUSDT",
    "ZECUSDT", "ZENUSDT", "ZETAUSDT", "ZILUSDT", "ZKUSDT", "ZKPUSDT", "ZORAUSDT", "ZROUSDT", "ZRXUSDT"
]

# 导出字典供其他模块使用
STATIC_SYMBOLS = {
    "okx": OKX_USDT_SWAPS,
    "binance": BINANCE_USDT_PERPETUALS
}


